apiVersion: batch/v1
kind: Job
metadata:
  name: web-content-copy
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: content-copy
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - 'echo "<html><head><title>Test Page</title></head><body><h1>Hello from Kubernetes NFS!</h1><p>This content is served from a pod using NFS storage.</p><p>Current time: $(date)</p></body></html>" > /data/index.html'
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: nfs-pvc