apiVersion: batch/v1
kind: Job
metadata:
  name: content-copy-job
spec:
  template:
    spec:
      containers:
      - name: content-copy
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - echo "Hello Kubernetes!" > /usr/share/nginx/html/index.html
        volumeMounts:
        - name: web-content
          mountPath: /usr/share/nginx/html
      restartPolicy: Never
      volumes:
      - name: web-content
        persistentVolumeClaim:
          claimName: nfs-pvc